/**:
  ros__parameters:
    wheel_radius: 0.115
    wheel_width: 0.100
    wheel_base: 0.600
    wheel_tread: 0.500
    front_overhang: 0.150
    rear_overhang: 0.130
    left_overhang: 0.050
    right_overhang: 0.050
    vehicle_height: 0.515
    max_steer_angle: 0.349
