set(_AMENT_PACKAGE_NAME "autoware_kalman_filter")
set(autoware_kalman_filter_VERSION "1.7.0")
set(autoware_kalman_filter_MAINTAINER "Yukihiro Saito <yukihiro.saito@tier4.jp>, Yamato Ando <yamato.ando@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>, NGUYEN Viet Anh <anh.nguyen.2@tier4.jp>, Taiki Yamada <taiki.yamada@tier4.jp>")
set(autoware_kalman_filter_BUILD_DEPENDS "eigen" "eigen3_cmake_module")
set(autoware_kalman_filter_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(autoware_kalman_filter_BUILD_EXPORT_DEPENDS )
set(autoware_kalman_filter_BUILDTOOL_EXPORT_DEPENDS )
set(autoware_kalman_filter_EXEC_DEPENDS )
set(autoware_kalman_filter_TEST_DEPENDS "ament_cmake_cppcheck" "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(autoware_kalman_filter_GROUP_DEPENDS )
set(autoware_kalman_filter_MEMBER_OF_GROUPS )
set(autoware_kalman_filter_DEPRECATED "")
set(autoware_kalman_filter_EXPORT_TAGS)
list(APPEND autoware_kalman_filter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
