set(_AMENT_PACKAGE_NAME "autoware_ekf_localizer")
set(autoware_ekf_localizer_VERSION "1.7.0")
set(autoware_ekf_localizer_MAINTAINER "Takamasa Horibe <takamasa.horibe@tier4.jp>, Yamato Ando <yamato.ando@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>, NGUYEN Viet Anh <anh.nguyen.2@tier4.jp>, Taiki Yamada <taiki.yamada@tier4.jp>")
set(autoware_ekf_localizer_BUILD_DEPENDS "eigen" "autoware_agnocast_wrapper" "autoware_internal_debug_msgs" "autoware_kalman_filter" "autoware_localization_util" "autoware_utils_geometry" "autoware_utils_logging" "autoware_utils_system" "diagnostic_msgs" "fmt" "geometry_msgs" "nav_msgs" "rclcpp" "rclcpp_components" "std_srvs" "tf2" "tf2_ros")
set(autoware_ekf_localizer_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake" "eigen3_cmake_module")
set(autoware_ekf_localizer_BUILD_EXPORT_DEPENDS "autoware_agnocast_wrapper" "autoware_internal_debug_msgs" "autoware_kalman_filter" "autoware_localization_util" "autoware_utils_geometry" "autoware_utils_logging" "autoware_utils_system" "diagnostic_msgs" "fmt" "geometry_msgs" "nav_msgs" "rclcpp" "rclcpp_components" "std_srvs" "tf2" "tf2_ros")
set(autoware_ekf_localizer_BUILDTOOL_EXPORT_DEPENDS )
set(autoware_ekf_localizer_EXEC_DEPENDS "autoware_agnocast_wrapper" "autoware_internal_debug_msgs" "autoware_kalman_filter" "autoware_localization_util" "autoware_utils_geometry" "autoware_utils_logging" "autoware_utils_system" "diagnostic_msgs" "fmt" "geometry_msgs" "nav_msgs" "rclcpp" "rclcpp_components" "std_srvs" "tf2" "tf2_ros")
set(autoware_ekf_localizer_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common" "launch_testing_ament_cmake" "ros_testing")
set(autoware_ekf_localizer_GROUP_DEPENDS )
set(autoware_ekf_localizer_MEMBER_OF_GROUPS )
set(autoware_ekf_localizer_DEPRECATED "")
set(autoware_ekf_localizer_EXPORT_TAGS)
list(APPEND autoware_ekf_localizer_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
