/**:
  ros__parameters:
    stream: tcpcli://192.168.1.200:21000
    reconnect_delay: 5.0
    delay_warning: 0.03

    messages:
      - "FP_A-ODOMETRY"
      - "FP_A-ODOMENU"
      - "FP_A-ODOMSH"
      - "FP_A-ODOMSTATUS"
      - "FP_A-EOE"
      - "FP_A-TF"
      - "FP_A-RAWIMU"
      - "FP_A-CORRIMU"
      - "FP_A-LLH"
      - "NOV_B-INSPVAX"

    fusion_epoch: true
    nmea_epoch: ""
    raw_output: false
    cov_warning: false
    nav2_mode: false

    converter:
      enabled: false
      topic_type: "Twist"
      input_topic: ""
      scale_factor: 1000.0
      use_x: true
      use_y: false
      use_z: false

    output_ns: "fixposition"
    speed_topic: "/fixposition/speed"
    corr_topic: "/rtcm"
    qos_type: "sensor_short"
