# CMake generated Testfile for 
# Source directory: /opt/ipg/carmaker/linux64-15.1/autoracer_hooke/vendor_ws/src/autoware/universe/localization/autoware_pose_covariance_modifier
# Build directory: /opt/ipg/carmaker/linux64-15.1/autoracer_hooke/cross_scene_heading_build/autoware_pose_covariance_modifier
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_pose_covariance_modifier "/opt/anaconda3/bin/python3" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/opt/ipg/carmaker/linux64-15.1/autoracer_hooke/cross_scene_heading_build/autoware_pose_covariance_modifier/test_results/autoware_pose_covariance_modifier/test_pose_covariance_modifier.gtest.xml" "--package-name" "autoware_pose_covariance_modifier" "--output-file" "/opt/ipg/carmaker/linux64-15.1/autoracer_hooke/cross_scene_heading_build/autoware_pose_covariance_modifier/ament_cmake_gtest/test_pose_covariance_modifier.txt" "--command" "/opt/ipg/carmaker/linux64-15.1/autoracer_hooke/cross_scene_heading_build/autoware_pose_covariance_modifier/test_pose_covariance_modifier" "--gtest_output=xml:/opt/ipg/carmaker/linux64-15.1/autoracer_hooke/cross_scene_heading_build/autoware_pose_covariance_modifier/test_results/autoware_pose_covariance_modifier/test_pose_covariance_modifier.gtest.xml")
set_tests_properties(test_pose_covariance_modifier PROPERTIES  LABELS "gtest" REQUIRED_FILES "/opt/ipg/carmaker/linux64-15.1/autoracer_hooke/cross_scene_heading_build/autoware_pose_covariance_modifier/test_pose_covariance_modifier" TIMEOUT "60" WORKING_DIRECTORY "/opt/ipg/carmaker/linux64-15.1/autoracer_hooke/cross_scene_heading_build/autoware_pose_covariance_modifier" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_auto/cmake/ament_auto_add_gtest.cmake;113;ament_add_gtest_test;/opt/ipg/carmaker/linux64-15.1/autoracer_hooke/vendor_ws/src/autoware/universe/localization/autoware_pose_covariance_modifier/CMakeLists.txt;18;ament_auto_add_gtest;/opt/ipg/carmaker/linux64-15.1/autoracer_hooke/vendor_ws/src/autoware/universe/localization/autoware_pose_covariance_modifier/CMakeLists.txt;0;")
subdirs("gtest")
