# Feedback data related to hooke2.0 ultr-sensors 2-5 report.

std_msgs/Header header

float64 uiuss5_tof_indirect	#  ultr sensor 5 indirect data, unit: cm, [0, 65535]
float64 uiuss4_tof_indirect	#  ultr sensor 4 indirect data, unit: cm, [0, 65535]
float64 uiuss3_tof_indirect	#  ultr sensor 3 indirect data, unit: cm, [0, 65535]
float64 uiuss2_tof_indirect	#  ultr sensor 2 indirect data, unit: cm, [0, 65535]
