# Feedback data related to hooke2.0 ultr-sensors 8-11 report.

std_msgs/Header header

float64 uiuss9_tof_indirect	#  ultr sensor 9 indirect data, unit: cm, [0, 65535]
float64 uiuss8_tof_indirect	#  ultr sensor 8 indirect data, unit: cm, [0, 65535]
float64 uiuss11_tof_indirect	#  ultr sensor 11 indirect data, unit: cm, [0, 65535]
float64 uiuss10_tof_indirect	#  ultr sensor 10 indirect data, unit: cm, [0, 65535]
