set(_AMENT_PACKAGE_NAME "autoware_pose_covariance_modifier")
set(autoware_pose_covariance_modifier_VERSION "0.50.0")
set(autoware_pose_covariance_modifier_MAINTAINER "Melike Tanrikulu <melike@leodrive.ai>")
set(autoware_pose_covariance_modifier_BUILD_DEPENDS "autoware_interpolation" "fixposition_driver_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "std_msgs")
set(autoware_pose_covariance_modifier_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(autoware_pose_covariance_modifier_BUILD_EXPORT_DEPENDS "autoware_interpolation" "fixposition_driver_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "std_msgs")
set(autoware_pose_covariance_modifier_BUILDTOOL_EXPORT_DEPENDS )
set(autoware_pose_covariance_modifier_EXEC_DEPENDS "autoware_interpolation" "fixposition_driver_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "std_msgs")
set(autoware_pose_covariance_modifier_TEST_DEPENDS "ament_cmake_gtest")
set(autoware_pose_covariance_modifier_GROUP_DEPENDS )
set(autoware_pose_covariance_modifier_MEMBER_OF_GROUPS )
set(autoware_pose_covariance_modifier_DEPRECATED "")
set(autoware_pose_covariance_modifier_EXPORT_TAGS)
list(APPEND autoware_pose_covariance_modifier_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
